config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :parks, only: [:index, :show] do
      resources :sightings, only: [:index, :new]
    end 

    resources :sightings

    resources :species, only: [:index, :show] do 
      resources :users, only: [:index]
    end 

    get '/dashboard', to: 'users#show' 

    root 'application#hello'




end

app/models/sighting.rb
class Sighting < ApplicationRecord
    belongs_to :user
    belongs_to :species
    belongs_to :park


    validates :species_id, presence: true
    validates :park_id, presence: true 
    validates :date, presence: true
    validates :date, uniqueness: { scope: [:species_id, :park_id, :user_id], message: ->(object, data) { ": You already made this entry!" }}


    def self.user_is(id)
        Sighting.where(user_id: id)
    end 

    def species_attributes=(species)
        if this_species = Species.find_by(name: species[:name], kingdom: species[:kingdom])
            self.species = this_species
        else 
            self.species = Species.create(species)
        end
    end

    def park_attributes=(park)
        if park[:name] && !park[:name].empty?
            if this_park = Park.find_by(name: park[:name])
                self.park = this_park
            else 
                self.park = Park.create(park)
            end 
        end 
    end
    
    def self.ordered_dates(id)
        dates = []
        self.where(user_id: id).order(:date).map do |sighting|
            dates << sighting.date
        end
        dates.uniq
    end 
    
    def self.by_date(date)
        self.where(date: date).order(:name)
    end
    

end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController

  before_action :require_login

  def show 
    require_be_current_user
    @sighting = Sighting.find(params[:id])
  end

  def index
    if pid = params[:park_id]
      @dates = Sighting.where(park_id: pid).ordered_dates(current_user.id)
    else 
      @dates = Sighting.ordered_dates(current_user.id)
    end
  end

  def new
    @parks = alphabetize(Park.all)
    @sighting = current_user.sightings.build
    @sighting.species = @sighting.build_species
    @sighting.park = @sighting.build_park unless @park_id = params[:park_id]
  end
  
  def create
    @sighting = Sighting.new(sighting_params)
    if @sighting.save
      redirect_to sighting_path(@sighting)
    else 
      @parks = alphabetize(Park.all)
      @sighting.species ||= @sighting.build_species
      @sighting.park ||= @sighting.build_park unless @park_id = params[:park_id]
      render :new
    end 
  end 
  
  def edit
    @parks = alphabetize(Park.all)
    @sighting = Sighting.find(params[:id])
    @sighting.species = @sighting.build_species unless @sighting.species
    @sighting.park = @sighting.build_park unless @sighting.park_id
  end

  def update
    @sighting = Sighting.find(params[:id])
    if @sighting.update(sighting_params)
      redirect_to sighting_path(@sighting)
    else 
      @parks = alphabetize(Park.all)
      @sighting.species ||= @sighting.build_species
      @sighting.park ||= @sighting.build_park unless @park_id = params[:park_id]
      render :new
    end 
  end 

  def destroy
    Sighting.find(params[:id]).destroy
    redirect_to root_url
  end 
  
  private
  
  def sighting_params
    params.require(:sighting).permit(:date, :user_id, :park_id, park_attributes: [:id, :name, :location, :size],  species_attributes: [:name, :kingdom])
  end

  def require_login
    return head(:forbidden) unless session.include? :session_id
  end

  def require_be_current_user
    unless current_sighting_user_id == current_user.id
      flash.alert = "Sorry! You can't look at this sighting. It belongs to another user."
      redirect_to root_url 
    end
  end

  def current_sighting_user_id
    Sighting.find(params[:id]).user_id
  end

  

end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/sightings/_form.html.erb
<% if @sighting.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(sighting.errors.count, "error") %>
      prohibited this sighting from being saved:
    </h2>
 
    <ul>
    <% sighting.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field_with_errors">
<%= form_for sighting do |f| %>
    <h3>Date:</h3>
    <%= f.date_field :date, max: Date.today %><br>
    <br>
    
    <h3>Species</h3>
    <%= f.fields_for :species do |sf| %>
        <%= sf.label :name, "Name:" %>
        <%= sf.text_field :name %>
        <br>
        <%= sf.label :kingdom, "Kingdom:" %>
        <%= sf.select(:kingdom, Species.kingdoms, {include_blank: true}) %>
    <% end %>

    <br>
    <br>
    
    <% if pid %>
      <%= hidden_field_tag :"sighting[park_id]", pid %>
    <% else %> 
      <h3>Park</h3>
      Existing Park:
      <%= f.collection_select(:park_id, parks, :id, :name, prompt: true) %>
      <h4>OR</h4>
      <%= f.fields_for :park, Park.new do |pf| %>
          Add New Park:<br>
          <%= pf.label :name, "Name:" %>
          <%= pf.text_field :name %>
          <br>
          <%= pf.label :location, "State:" %>
          <%= pf.select(:location, us_states, {include_blank: true}) %>
          <br>
          <%= pf.label :size, "Size (square miles):" %>
          <%= pf.number_field :size %>
          <br>
      <% end %>
    <% end %>
      
    <%= f.hidden_field(:user_id, value: sighting.user_id) %>
            
    <%= f.submit "Add Sighting" %>
<% end %>
</div>

app/views/sightings/edit.html.erb
<h1>Edit Sighting</h1>
<%= render partial: "form", locals: {sighting: @sighting, pid: @park_id, parks: @parks} %>

app/views/sightings/index.html.erb
<h1>Sightings:</h1>
<%= render partial: "./sightings_index", locals: {dates: @dates} %>

app/views/sightings/new.html.erb
<h1>Add New Sighting!</h1>
<%= render partial: "form", locals: {sighting: @sighting, pid: @park_id, parks: @parks} %>

app/views/sightings/show.html.erb
<h2>A wild <%= @sighting.species.name %> appeared!</h2>
<h3> You spotted a <%= link_to @sighting.species.name, species_path(@sighting.species) %> on <%= @sighting.date.strftime("%B %e, %Y") %> in <%= link_to "#{@sighting.park.name} National Park", park_path(@sighting.park) %>. </h3>
<p><%= link_to "Edit", edit_sighting_url %></p>
<%= link_to "Delete", @sighting, method: :delete, data: { confirm: "Are you sure you want to delete this sighting record?" } %>