config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :parks, only: [:index, :show] do
      resources :sightings, only: [:index, :new]
    end 

    resources :sightings

    resources :species, only: [:index, :show] do 
      resources :users, only: [:index]
    end 

    get '/dashboard', to: 'users#show' 

    root 'application#hello'




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P a r k T r a c k</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
        .header {
          position: fixed;
          width: 100%;
          height:70px;
          background-color: white;
          color: white;
          text-align: left;
        }

        body {
          background-image: url("/background-image.png");
          background-attachment: fixed;
          background-repeat: no-repeat;
          font-family: "Lucida Console", Monaco, monospace;
          line-height: 18px;
        }

        .footer {
          position:fixed;
          left: 0;
          bottom: 0;
          width: 100%;
          height:22px;
          color: white;
          text-align: center;
          background:honeydew;
        }
      </style>
    </head>

  <body>

    
    
    <h1 style="font-size:40px;text-align:center"><%= link_to "ParkTrack", root_path %></h1>
    
    <% if user_signed_in? %>
      <p style="text-align:center;">
        <%= link_to "Record A New Sighting!", new_sighting_path %>
      </p>
    <% else %>
      <p style="text-align:center;">
        <%= link_to "Sign In", new_user_session_path %>
      </p>
    <% end %>

    <%= yield %>

    <div class="footer">
      <% if user_signed_in? %>
        <%= link_to "Dashboard", dashboard_path %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      <% end %>
    </div>
    <br>
  </body>
</html>